//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rss.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public Feed()
        {
            this.Items = new HashSet<Item>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> FolderId { get; set; }
        public Nullable<System.DateTime> LastUpdateDateTime { get; set; }
        public string FeedUrl { get; set; }
        public string HtmlUrl { get; set; }
        public Nullable<System.DateTime> LastBuildDate { get; set; }
        public string UpdatePeriod { get; set; }
        public string UpdateFrequency { get; set; }
        public string FavIcon { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
